### ISSUE TITLE
Autorun snapshots in CI to avoid dead code

### ISSUE THREAD

**Issue by BioPhoton** [flowup/quality-metrics-cli#140]
There's no .toMatchSnapshot(), so the .snap file can be deleted. If you run with -u, it will delete obsolete snapshots.

**Comment by matejchalk** [comment]
Unfortunately, it's not that simple. If you add `-u` in CI, then every snapshot test will always pass. The primary effect of `-u` is to replace snapshots that didn't match (i.e. if you want to automatically change your assertion), removing obsolete snapshots is a secondary effect. 

https://vitest.dev/guide/snapshot.html#updating-snapshots

The ideal would be to have a "fail if there are obsolete snapshots" flag, but I couldn't find anything like that.
