### ISSUE TITLE
Move core logic into new "core" package

### ISSUE THREAD

**Issue by matejchalk** [flowup/quality-metrics-cli#73]
## Proposal

- all our core logic that's not Yargs-related lives in `utils` - too much?
- `utils` could be only for more generic helper functions, e.g. `executeProcess` or Markdown formatters
- core logic like `collect` and `executePlugin` could live in `core` package

## Motivation

- `core` package should be for programmatic usage of our core logic (e.g. used by our GitHub Action)
- cleaner separation of core and plugin layers - `plugin-*` packages can import from `utils` or `models`, but not from `core`
- the `cli` project might not then need multiple entry points (only bin)
- having separate `cli` and `core` is quite common in other CLI-first projects (e.g. [jest](https://github.com/jestjs/jest/tree/main/packages) or [graphql-code-generator](https://github.com/dotansimha/graphql-code-generator/tree/master/packages))

## Nx graph

![Image](https://github.com/flowup/quality-metrics-cli/assets/34691111/7d548d48-1dd0-4271-a9ae-50b99619afd0)

**Comment by BioPhoton** [comment]
As this refactoring is pretty involved in the whole code base i suggest the changes in the following order:

1. Prepare the codebase for the move - especially functions that will move should file in independent fils
  1.1. utils: #78 
  1.2. cli: #80  #79
2. Create the new core package
3. Move files from cli to utils and core
4. Move files from utils to core

**Comment by matejchalk** [comment]
Closing since all the mentioned PRs have been merged.
