### ISSUE TITLE
Format options should process `md,stdout` to an array

### ISSUE THREAD

**Issue by BioPhoton** [flowup/quality-metrics-cli#95]
- Figure out what is the official separator and then change it
- Look up in yargs documentation
- Split up stings based up on separator

**Comment by ChristopherPHolder** [comment]
This is probably relevant.

https://yargs.js.org/docs/#api-reference-arraykey

**Comment by BioPhoton** [comment]
Thx @ChristopherPHolder this closes this issue i would say
